import { z } from "zod";
import { listLanguages } from "youtube-transcript-plus";
import { parseVideoId } from "../utils/parse-video-id.js";

export const getTranscriptLanguagesSchema = z.object({
  video: z
    .string()
    .min(1, "Video URL or ID is required")
    .trim()
    .describe("YouTube video URL or video ID"),
});

export async function getTranscriptLanguages(
  args: z.infer<typeof getTranscriptLanguagesSchema>
) {
  let videoId: string;
  try {
    videoId = parseVideoId(args.video);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    return { content: [{ type: "text" as const, text: `❌ Invalid video: ${msg}` }], isError: true };
  }

  try {
    const languages = await listLanguages(videoId);

    if (!languages || languages.length === 0) {
      return {
        content: [{ type: "text" as const, text: "No captions available for this video." }],
      };
    }

    const manual = languages.filter((l) => !l.isAutoGenerated);
    const auto = languages.filter((l) => l.isAutoGenerated);

    const lines: string[] = [
      `🌐 Available transcript languages for video ${videoId}:\n`,
      `Total: ${languages.length} track(s) — ${manual.length} manual, ${auto.length} auto-generated\n`,
    ];

    if (manual.length > 0) {
      lines.push("Manual captions:");
      for (const lang of manual) {
        lines.push(`  • ${lang.languageName} (code: "${lang.languageCode}")`);
      }
    }

    if (auto.length > 0) {
      lines.push("\nAuto-generated captions:");
      for (const lang of auto) {
        lines.push(`  • ${lang.languageName} (code: "${lang.languageCode}") [auto]`);
      }
    }

    lines.push(`\n💡 Use the language code with get_video_transcript (e.g. lang="${languages[0].languageCode}")`);

    return { content: [{ type: "text" as const, text: lines.join("\n") }] };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);

    if (msg.includes("disabled") || msg.includes("not available") || msg.includes("Could not")) {
      return {
        content: [{ type: "text" as const, text: "Captions are disabled or unavailable for this video." }],
      };
    }

    return { content: [{ type: "text" as const, text: `❌ Failed to fetch transcript languages: ${msg}` }], isError: true };
  }
}
