import { z } from "zod";
import { listLanguages } from "youtube-transcript-plus";
import { parseVideoId } from "../utils/parse-video-id.js";

export const getTranscriptLanguagesSchema = z.object({
  video: z
    .string()
    .min(1, "Video URL or ID is required")
    .trim()
    .describe("YouTube video URL or video ID"),
});

const transcriptLanguageSchema = z.object({
  languageCode: z.string(),
  languageName: z.string(),
  isAutoGenerated: z.boolean(),
});

export const getTranscriptLanguagesOutputSchema = {
  videoId: z.string(),
  available: z.boolean(),
  totalTracks: z.number().int().min(0),
  manualCount: z.number().int().min(0),
  autoGeneratedCount: z.number().int().min(0),
  message: z.string().optional(),
  languages: z.array(transcriptLanguageSchema),
};

export async function getTranscriptLanguages(
  args: z.infer<typeof getTranscriptLanguagesSchema>
) {
  let videoId: string;
  try {
    videoId = parseVideoId(args.video);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    return { content: [{ type: "text" as const, text: `❌ Invalid video: ${msg}` }], isError: true };
  }

  try {
    const languages = await listLanguages(videoId);
    const normalizedLanguages = languages.map((lang) => ({
      languageCode: lang.languageCode,
      languageName: lang.languageName,
      isAutoGenerated: lang.isAutoGenerated,
    }));

    if (!languages || languages.length === 0) {
      const structuredContent = {
        videoId,
        available: false,
        totalTracks: 0,
        manualCount: 0,
        autoGeneratedCount: 0,
        message: "No captions available for this video.",
        languages: [],
      };

      return {
        content: [{ type: "text" as const, text: "No captions available for this video." }],
        structuredContent,
      };
    }

    const manual = normalizedLanguages.filter((l) => !l.isAutoGenerated);
    const auto = normalizedLanguages.filter((l) => l.isAutoGenerated);

    const lines: string[] = [
      `🌐 Available transcript languages for video ${videoId}:\n`,
      `Total: ${normalizedLanguages.length} track(s) — ${manual.length} manual, ${auto.length} auto-generated\n`,
    ];

    if (manual.length > 0) {
      lines.push("Manual captions:");
      for (const lang of manual) {
        lines.push(`  • ${lang.languageName} (code: "${lang.languageCode}")`);
      }
    }

    if (auto.length > 0) {
      lines.push("\nAuto-generated captions:");
      for (const lang of auto) {
        lines.push(`  • ${lang.languageName} (code: "${lang.languageCode}") [auto]`);
      }
    }

    lines.push(`\n💡 Use the language code with get_video_transcript (e.g. lang="${normalizedLanguages[0].languageCode}")`);

    return {
      content: [{ type: "text" as const, text: lines.join("\n") }],
      structuredContent: {
        videoId,
        available: true,
        totalTracks: normalizedLanguages.length,
        manualCount: manual.length,
        autoGeneratedCount: auto.length,
        languages: normalizedLanguages,
      },
    };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);

    if (msg.includes("disabled") || msg.includes("not available") || msg.includes("Could not")) {
      return {
        content: [{ type: "text" as const, text: "Captions are disabled or unavailable for this video." }],
        structuredContent: {
          videoId,
          available: false,
          totalTracks: 0,
          manualCount: 0,
          autoGeneratedCount: 0,
          message: "Captions are disabled or unavailable for this video.",
          languages: [],
        },
      };
    }

    return { content: [{ type: "text" as const, text: `❌ Failed to fetch transcript languages: ${msg}` }], isError: true };
  }
}
